SELECT codigo_pais, nombre_pais 
FROM tbl_paises 
WHERE nombre_pais = 'Colombia';

SELECT *
FROM tbl_invitados
WHERE GENERO = 'F'
OR DIRECCION = 'Col Kennedy';
/*
&&--> AND 
|| --> OR
! --> NOT
*/

/*PARA FILTRAR NULOS SE DEBE UTILIZAR IS NULL*/
SELECT *
FROM TBL_EVENTOS
WHERE DESCRIPCION IS NULL;

/* BETWEEN */

SELECT *
FROM TBL_EVENTOS
WHERE CANTIDAD_INVITADOS >=50 
AND  CANTIDAD_INVITADOS <=150;

SELECT *
FROM TBL_EVENTOS
WHERE CANTIDAD_INVITADOS BETWEEN 50 AND 150;

/*IN*/
SELECT *
FROM TBL_EVENTOS
WHERE CODIGO_TIPO_EVENTO IN (2,4,7);

SELECT *
FROM TBL_EVENTOS
WHERE CODIGO_TIPO_EVENTO = 2
OR CODIGO_TIPO_EVENTO = 4
OR CODIGO_TIPO_EVENTO = 7;


/* LIKE */
SELECT *
FROM TBL_INVITADOS
WHERE NOMBRE_INVITADO LIKE '%Rod%';

SELECT *
FROM TBL_INVITADOS
WHERE NOMBRE_INVITADO LIKE '%ez';

SELECT *
FROM TBL_INVITADOS
WHERE NOMBRE_INVITADO LIKE 'Ma%';


SELECT *
FROM TBL_INVITADOS
WHERE NOMBRE_INVITADO LIKE '%A%ri%'; 

